### ISSUE TITLE
Example of Request Code and Connection Requirements for LTI integration 

### ISSUE THREAD

**Issue by HectorRojasB** [longhornopen/laravel-celtic-lti#15]
We are currently working on integrating a Learning Management System (LMS) into a Laravel-based project. However, we are facing difficulties in establishing a connection through a POST request to the LMS, as we lack a code example to guide us. We also have uncertainties about the necessary requirements to make the connection, as we are unsure about the underlying technology of the LMS. To address these concerns, we have compiled several parameters provided by the LMS administrators that could be relevant:

**1. Example of Request Code: If someone in the community could provide us with a code example to make a request to the LMS, it would be greatly helpful in understanding how to structure the connection from our Laravel project.**

**2. Required Connection Data: Since we do not have information about the underlying technology of the LMS, we would like to know what data is essential to establish the connection correctly. The LMS administrators have provided us with the following data:**

```
Tool URL
Public keyset URL
Initiate Login URL
Redirection URI(s)
```

If any documentation is available or if anyone has worked with this specific LMS, we would appreciate any guidance on how to use this data in our connection and communication with the LMS.

**3. URL and Server Requirements: We are currently in the local testing phase, so we would like to confirm if it is necessary to be in a server environment to establish the connection with the LMS. Is having a specific login URL mandatory for this connection, or are there alternatives?**

If you can provide any information to help address these concerns, we would greatly appreciate your collaboration.

Thanks!

**Comment by chrispittman** [comment]
Check the 'wiki' tab in this Github repo, if you haven't already.

1. There's a basic example in the wiki.  I also have a test app that demonstrates some more advanced LMS integration.  I'll clean it up and put it online sometime this week.
2. The `php artisan lti:add_platform_1.3` command will walk you through how to get this information into the database.
3. You don't need a publically-accessible URL in order to test with.  You do need to tell the LMS the URL of your server, but it's okay for that URL to be 'http://localhost' or something similar.

**Comment by chrispittman** [comment]
See https://github.com/longhornopen/lti-example-app for an example app using this library.

Do you have any questions?  Is all this clear, or are there parts we can document better?
